module.exports = {
  apps: [
    {
      name: "fxincap-app",
      cwd: "/var/www/fxincap-staging/fxincap",
      script: "pnpm",
      args: "start",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "staging",
        PORT: 4000,
      },
      error_file: "/var/www/fxincap-staging/logs/fxincap-error.log",
      out_file: "/var/www/fxincap-staging/logs/fxincap-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
    {
      name: "fxincap-admin",
      cwd: "/var/www/fxincap-staging/fxincapadmin",
      script: "pnpm",
      args: "run start",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "staging",
        PORT: 5001,
      },
      error_file: "/var/www/fxincap-staging/logs/fxincapadmin-error.log",
      out_file: "/var/www/fxincap-staging/logs/fxincapadmin-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
    {
      name: "fxincap-api",
      cwd: "/var/www/fxincap-staging/fxincapapi",
      script: "node",
      args: "dist/index.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "staging",
        PORT: 7000,
      },
      error_file: "/var/www/fxincap-staging/logs/fxincapapi-error.log",
      out_file: "/var/www/fxincap-staging/logs/fxincapapi-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
    {
      name: "fxincap-trade",
      cwd: "/var/www/fxincap-staging/fxincaptrade",
      script: "node",
      args: "dist/server/start.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "staging",
        PORT: 3000,
      },
      error_file: "/var/www/fxincap-staging/logs/fxincaptrade-error.log",
      out_file: "/var/www/fxincap-staging/logs/fxincaptrade-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
    {
      name: "fxincap-ws",
      cwd: "/var/www/fxincap-staging/fxincapws",
      script: "src/server.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "staging",
        WS_PORT: 4040,
      },
      error_file: "/var/www/fxincap-staging/logs/fxincapws-error.log",
      out_file: "/var/www/fxincap-staging/logs/fxincapws-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
  ],
};
